version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  run:
    desc: "run the project in dev local environment"
    cmds:
      - go run github.com/air-verse/air@latest
  gen-dotenv:
    desc: "generate .env file from infra.Config struct"
    cmds:
      - go run ./tools/dotenv-gen > .env
      - cp .env .env_sample
  watch:
    dir: web
    cmds:
      - npm run watch